export enum CURRENCY_SYMBOL {
  USD = 'USD',
  EUR = 'EUR',
  GBP = 'GBP',
  JPY = 'JPY',
  KRW = 'KRW',
  CNY = 'CNY',
  CHF = 'CHF',
  AUD = 'AUD',
  CAD = 'CAD',
  SEK = 'SEK',
  NOK = 'NOK',
  NZD = 'NZD',
  MXN = 'MXN',
  BRL = 'BRL',
  INR = 'INR',
  RUB = 'RUB',
  ZAR = 'ZAR',
}
